issue-114: update refresh method to GET from POST
senacor/elasticsearch-evolution pull request #118
Opened 2022-03-30 16:43 UTC by ttj4

2022-03-30 18:59 UTC, xtermi2 requested changes

2022-03-30 18:59 UTC, xtermi2 commented on elasticsearch-evolution-core/src/main/java/com/senacor/elasticsearch/evolution/core/internal/migration/execution/HistoryRepositoryImpl.java
> +            System.out.println(refreshParams(IndicesOptions.lenientExpandOpen()));
Nothing should be logge with `System.out` use the already existing `logger` and create a more meaningfull message, like 
```java
String refreshParams = refreshParams(IndicesOptions.lenientExpandOpen());
logger.debug("refreshing indices {} with params '{}'", Arrays.toString(indices), refreshParams);
```
and reuse `refreshParams` later in the `Request` .

2022-03-30 18:59 UTC, xtermi2 commented on elasticsearch-evolution-core/src/test/java/com/senacor/elasticsearch/evolution/core/internal/migration/execution/HistoryRepositoryImplTest.java
>              when(restHighLevelClient.indices().refresh(any(), eq(RequestOptions.DEFAULT)).getStatus())
I think this can be deleted

2022-03-31 01:31 UTC, ttj4 commented on elasticsearch-evolution-core/src/main/java/com/senacor/elasticsearch/evolution/core/internal/migration/execution/HistoryRepositoryImpl.java
> +            System.out.println(refreshParams(IndicesOptions.lenientExpandOpen()));
yeah I agree, changed now.  I didn't realize I had put a system.out!

2022-03-31 01:32 UTC, ttj4 commented on elasticsearch-evolution-core/src/test/java/com/senacor/elasticsearch/evolution/core/internal/migration/execution/HistoryRepositoryImplTest.java
>              when(restHighLevelClient.indices().refresh(any(), eq(RequestOptions.DEFAULT)).getStatus())
done

2022-03-31 06:03 UTC, xtermi2 approved these changes

2022-03-31 06:15 UTC, xtermi2 commented
@ttj4 you can ignore the failed pipeline and merge. This is an issue in the pipeline when a PR is running from a forked repo. I think I already fixed this.

2022-03-31 14:33 UTC, ttj4 commented
@xtermi2 will you be able to merge this? I'm not authorized to merge the PR

2022-03-31 14:34 UTC, merged